version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: yahoofinance
    ports:
      - "5432:5432"
  
  app:
    build: .
    container_name: scrap-yahoo-finance
    depends_on:
      - db
    command: python load.py
